service: serverless-disasm-duvallj-pw

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerFile: ./Dockerfile

package:
  patterns:
    - '!flask_session/**'
    - '!venv/**'
    - '!keystone/**'
    - '!venv-run.sh'
    - 'static/js/libs/ace/src-min-noconflict/ace.js'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
